// Generated by gencpp from file osrf_gear/AGVControl.msg
// DO NOT EDIT!


#ifndef OSRF_GEAR_MESSAGE_AGVCONTROL_H
#define OSRF_GEAR_MESSAGE_AGVCONTROL_H

#include <ros/service_traits.h>


#include <osrf_gear/AGVControlRequest.h>
#include <osrf_gear/AGVControlResponse.h>


namespace osrf_gear
{

struct AGVControl
{

typedef AGVControlRequest Request;
typedef AGVControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AGVControl
} // namespace osrf_gear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::osrf_gear::AGVControl > {
  static const char* value()
  {
    return "deaeee526929d0b28e9533c57234f4ca";
  }

  static const char* value(const ::osrf_gear::AGVControl&) { return value(); }
};

template<>
struct DataType< ::osrf_gear::AGVControl > {
  static const char* value()
  {
    return "osrf_gear/AGVControl";
  }

  static const char* value(const ::osrf_gear::AGVControl&) { return value(); }
};


// service_traits::MD5Sum< ::osrf_gear::AGVControlRequest> should match 
// service_traits::MD5Sum< ::osrf_gear::AGVControl > 
template<>
struct MD5Sum< ::osrf_gear::AGVControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::osrf_gear::AGVControl >::value();
  }
  static const char* value(const ::osrf_gear::AGVControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::osrf_gear::AGVControlRequest> should match 
// service_traits::DataType< ::osrf_gear::AGVControl > 
template<>
struct DataType< ::osrf_gear::AGVControlRequest>
{
  static const char* value()
  {
    return DataType< ::osrf_gear::AGVControl >::value();
  }
  static const char* value(const ::osrf_gear::AGVControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::osrf_gear::AGVControlResponse> should match 
// service_traits::MD5Sum< ::osrf_gear::AGVControl > 
template<>
struct MD5Sum< ::osrf_gear::AGVControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::osrf_gear::AGVControl >::value();
  }
  static const char* value(const ::osrf_gear::AGVControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::osrf_gear::AGVControlResponse> should match 
// service_traits::DataType< ::osrf_gear::AGVControl > 
template<>
struct DataType< ::osrf_gear::AGVControlResponse>
{
  static const char* value()
  {
    return DataType< ::osrf_gear::AGVControl >::value();
  }
  static const char* value(const ::osrf_gear::AGVControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OSRF_GEAR_MESSAGE_AGVCONTROL_H
