// Generated by gencpp from file osrf_gear/ConveyorBeltState.msg
// DO NOT EDIT!


#ifndef OSRF_GEAR_MESSAGE_CONVEYORBELTSTATE_H
#define OSRF_GEAR_MESSAGE_CONVEYORBELTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace osrf_gear
{
template <class ContainerAllocator>
struct ConveyorBeltState_
{
  typedef ConveyorBeltState_<ContainerAllocator> Type;

  ConveyorBeltState_()
    : power(0.0)  {
    }
  ConveyorBeltState_(const ContainerAllocator& _alloc)
    : power(0.0)  {
  (void)_alloc;
    }



   typedef double _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> const> ConstPtr;

}; // struct ConveyorBeltState_

typedef ::osrf_gear::ConveyorBeltState_<std::allocator<void> > ConveyorBeltState;

typedef boost::shared_ptr< ::osrf_gear::ConveyorBeltState > ConveyorBeltStatePtr;
typedef boost::shared_ptr< ::osrf_gear::ConveyorBeltState const> ConveyorBeltStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osrf_gear::ConveyorBeltState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace osrf_gear

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'osrf_gear': ['/home/chuanhui/ariac_ws/src/ariac/osrf_gear/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b61bda1d4e0075084b2082bebb59ea34";
  }

  static const char* value(const ::osrf_gear::ConveyorBeltState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb61bda1d4e007508ULL;
  static const uint64_t static_value2 = 0x4b2082bebb59ea34ULL;
};

template<class ContainerAllocator>
struct DataType< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osrf_gear/ConveyorBeltState";
  }

  static const char* value(const ::osrf_gear::ConveyorBeltState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Conveyor belt state message\n\
float64 power    # power of the belt (percentage, in +Y direction of belt frame)\n\
";
  }

  static const char* value(const ::osrf_gear::ConveyorBeltState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConveyorBeltState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osrf_gear::ConveyorBeltState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osrf_gear::ConveyorBeltState_<ContainerAllocator>& v)
  {
    s << indent << "power: ";
    Printer<double>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSRF_GEAR_MESSAGE_CONVEYORBELTSTATE_H
