// Generated by gencpp from file osrf_gear/GetMaterialLocations.msg
// DO NOT EDIT!


#ifndef OSRF_GEAR_MESSAGE_GETMATERIALLOCATIONS_H
#define OSRF_GEAR_MESSAGE_GETMATERIALLOCATIONS_H

#include <ros/service_traits.h>


#include <osrf_gear/GetMaterialLocationsRequest.h>
#include <osrf_gear/GetMaterialLocationsResponse.h>


namespace osrf_gear
{

struct GetMaterialLocations
{

typedef GetMaterialLocationsRequest Request;
typedef GetMaterialLocationsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMaterialLocations
} // namespace osrf_gear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::osrf_gear::GetMaterialLocations > {
  static const char* value()
  {
    return "cbf263a50360138b80b1bdd46f5ff56f";
  }

  static const char* value(const ::osrf_gear::GetMaterialLocations&) { return value(); }
};

template<>
struct DataType< ::osrf_gear::GetMaterialLocations > {
  static const char* value()
  {
    return "osrf_gear/GetMaterialLocations";
  }

  static const char* value(const ::osrf_gear::GetMaterialLocations&) { return value(); }
};


// service_traits::MD5Sum< ::osrf_gear::GetMaterialLocationsRequest> should match 
// service_traits::MD5Sum< ::osrf_gear::GetMaterialLocations > 
template<>
struct MD5Sum< ::osrf_gear::GetMaterialLocationsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::osrf_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::osrf_gear::GetMaterialLocationsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::osrf_gear::GetMaterialLocationsRequest> should match 
// service_traits::DataType< ::osrf_gear::GetMaterialLocations > 
template<>
struct DataType< ::osrf_gear::GetMaterialLocationsRequest>
{
  static const char* value()
  {
    return DataType< ::osrf_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::osrf_gear::GetMaterialLocationsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::osrf_gear::GetMaterialLocationsResponse> should match 
// service_traits::MD5Sum< ::osrf_gear::GetMaterialLocations > 
template<>
struct MD5Sum< ::osrf_gear::GetMaterialLocationsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::osrf_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::osrf_gear::GetMaterialLocationsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::osrf_gear::GetMaterialLocationsResponse> should match 
// service_traits::DataType< ::osrf_gear::GetMaterialLocations > 
template<>
struct DataType< ::osrf_gear::GetMaterialLocationsResponse>
{
  static const char* value()
  {
    return DataType< ::osrf_gear::GetMaterialLocations >::value();
  }
  static const char* value(const ::osrf_gear::GetMaterialLocationsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OSRF_GEAR_MESSAGE_GETMATERIALLOCATIONS_H
