// Generated by gencpp from file osrf_gear/Order.msg
// DO NOT EDIT!


#ifndef OSRF_GEAR_MESSAGE_ORDER_H
#define OSRF_GEAR_MESSAGE_ORDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <osrf_gear/Kit.h>

namespace osrf_gear
{
template <class ContainerAllocator>
struct Order_
{
  typedef Order_<ContainerAllocator> Type;

  Order_()
    : order_id()
    , kits()  {
    }
  Order_(const ContainerAllocator& _alloc)
    : order_id(_alloc)
    , kits(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _order_id_type;
  _order_id_type order_id;

   typedef std::vector< ::osrf_gear::Kit_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::osrf_gear::Kit_<ContainerAllocator> >::other >  _kits_type;
  _kits_type kits;





  typedef boost::shared_ptr< ::osrf_gear::Order_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osrf_gear::Order_<ContainerAllocator> const> ConstPtr;

}; // struct Order_

typedef ::osrf_gear::Order_<std::allocator<void> > Order;

typedef boost::shared_ptr< ::osrf_gear::Order > OrderPtr;
typedef boost::shared_ptr< ::osrf_gear::Order const> OrderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osrf_gear::Order_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osrf_gear::Order_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace osrf_gear

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'osrf_gear': ['/home/chuanhui/ariac_ws/src/ariac/osrf_gear/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::osrf_gear::Order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osrf_gear::Order_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osrf_gear::Order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osrf_gear::Order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osrf_gear::Order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osrf_gear::Order_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osrf_gear::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fadfe9b7f871f7a5285e3dfb4eb98ef";
  }

  static const char* value(const ::osrf_gear::Order_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fadfe9b7f871f7aULL;
  static const uint64_t static_value2 = 0x5285e3dfb4eb98efULL;
};

template<class ContainerAllocator>
struct DataType< ::osrf_gear::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osrf_gear/Order";
  }

  static const char* value(const ::osrf_gear::Order_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osrf_gear::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Order message\n\
# This structure contains the information of an order.\n\
\n\
# ID of the order\n\
string order_id\n\
\n\
# Collection of kits\n\
Kit[] kits\n\
\n\
================================================================================\n\
MSG: osrf_gear/Kit\n\
# Kit message\n\
# This structure contains the information of kit.\n\
\n\
# The type of kit\n\
string kit_type\n\
\n\
# Collection of objects\n\
KitObject[] objects\n\
\n\
================================================================================\n\
MSG: osrf_gear/KitObject\n\
# KitObject message\n\
# This structure contains the information of an object contained in a kit.\n\
\n\
# Object type\n\
string type\n\
\n\
# Target pose\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::osrf_gear::Order_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osrf_gear::Order_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order_id);
      stream.next(m.kits);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Order_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osrf_gear::Order_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osrf_gear::Order_<ContainerAllocator>& v)
  {
    s << indent << "order_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.order_id);
    s << indent << "kits[]" << std::endl;
    for (size_t i = 0; i < v.kits.size(); ++i)
    {
      s << indent << "  kits[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::osrf_gear::Kit_<ContainerAllocator> >::stream(s, indent + "    ", v.kits[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSRF_GEAR_MESSAGE_ORDER_H
