// Generated by gencpp from file osrf_gear/TrayContents.msg
// DO NOT EDIT!


#ifndef OSRF_GEAR_MESSAGE_TRAYCONTENTS_H
#define OSRF_GEAR_MESSAGE_TRAYCONTENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <osrf_gear/DetectedObject.h>

namespace osrf_gear
{
template <class ContainerAllocator>
struct TrayContents_
{
  typedef TrayContents_<ContainerAllocator> Type;

  TrayContents_()
    : tray()
    , objects()  {
    }
  TrayContents_(const ContainerAllocator& _alloc)
    : tray(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tray_type;
  _tray_type tray;

   typedef std::vector< ::osrf_gear::DetectedObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::osrf_gear::DetectedObject_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::osrf_gear::TrayContents_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::osrf_gear::TrayContents_<ContainerAllocator> const> ConstPtr;

}; // struct TrayContents_

typedef ::osrf_gear::TrayContents_<std::allocator<void> > TrayContents;

typedef boost::shared_ptr< ::osrf_gear::TrayContents > TrayContentsPtr;
typedef boost::shared_ptr< ::osrf_gear::TrayContents const> TrayContentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::osrf_gear::TrayContents_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::osrf_gear::TrayContents_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace osrf_gear

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'osrf_gear': ['/home/chuanhui/ariac_ws/src/ariac/osrf_gear/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::osrf_gear::TrayContents_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::osrf_gear::TrayContents_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osrf_gear::TrayContents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::osrf_gear::TrayContents_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osrf_gear::TrayContents_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::osrf_gear::TrayContents_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::osrf_gear::TrayContents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b61a478a5b617eeaaa8cf0fa99e60cc";
  }

  static const char* value(const ::osrf_gear::TrayContents_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b61a478a5b617eeULL;
  static const uint64_t static_value2 = 0xaaa8cf0fa99e60ccULL;
};

template<class ContainerAllocator>
struct DataType< ::osrf_gear::TrayContents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "osrf_gear/TrayContents";
  }

  static const char* value(const ::osrf_gear::TrayContents_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::osrf_gear::TrayContents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Tray contents message\n\
# This structure contains the information of the current contents of a tray.\n\
\n\
# The ID of the tray\n\
string tray\n\
\n\
# Collection of objects\n\
DetectedObject[] objects\n\
\n\
================================================================================\n\
MSG: osrf_gear/DetectedObject\n\
# DetectedObject message\n\
# This structure contains the information of a detected object.\n\
\n\
# Object type\n\
string type\n\
\n\
# Whether or not the object is faulty\n\
bool is_faulty\n\
\n\
# Target pose\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::osrf_gear::TrayContents_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::osrf_gear::TrayContents_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tray);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrayContents_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::osrf_gear::TrayContents_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::osrf_gear::TrayContents_<ContainerAllocator>& v)
  {
    s << indent << "tray: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tray);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::osrf_gear::DetectedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OSRF_GEAR_MESSAGE_TRAYCONTENTS_H
