// Generated by gencpp from file osrf_gear/VacuumGripperControl.msg
// DO NOT EDIT!


#ifndef OSRF_GEAR_MESSAGE_VACUUMGRIPPERCONTROL_H
#define OSRF_GEAR_MESSAGE_VACUUMGRIPPERCONTROL_H

#include <ros/service_traits.h>


#include <osrf_gear/VacuumGripperControlRequest.h>
#include <osrf_gear/VacuumGripperControlResponse.h>


namespace osrf_gear
{

struct VacuumGripperControl
{

typedef VacuumGripperControlRequest Request;
typedef VacuumGripperControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VacuumGripperControl
} // namespace osrf_gear


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::osrf_gear::VacuumGripperControl > {
  static const char* value()
  {
    return "6a0b406242562fc416b2c9c8a3efb051";
  }

  static const char* value(const ::osrf_gear::VacuumGripperControl&) { return value(); }
};

template<>
struct DataType< ::osrf_gear::VacuumGripperControl > {
  static const char* value()
  {
    return "osrf_gear/VacuumGripperControl";
  }

  static const char* value(const ::osrf_gear::VacuumGripperControl&) { return value(); }
};


// service_traits::MD5Sum< ::osrf_gear::VacuumGripperControlRequest> should match 
// service_traits::MD5Sum< ::osrf_gear::VacuumGripperControl > 
template<>
struct MD5Sum< ::osrf_gear::VacuumGripperControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::osrf_gear::VacuumGripperControl >::value();
  }
  static const char* value(const ::osrf_gear::VacuumGripperControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::osrf_gear::VacuumGripperControlRequest> should match 
// service_traits::DataType< ::osrf_gear::VacuumGripperControl > 
template<>
struct DataType< ::osrf_gear::VacuumGripperControlRequest>
{
  static const char* value()
  {
    return DataType< ::osrf_gear::VacuumGripperControl >::value();
  }
  static const char* value(const ::osrf_gear::VacuumGripperControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::osrf_gear::VacuumGripperControlResponse> should match 
// service_traits::MD5Sum< ::osrf_gear::VacuumGripperControl > 
template<>
struct MD5Sum< ::osrf_gear::VacuumGripperControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::osrf_gear::VacuumGripperControl >::value();
  }
  static const char* value(const ::osrf_gear::VacuumGripperControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::osrf_gear::VacuumGripperControlResponse> should match 
// service_traits::DataType< ::osrf_gear::VacuumGripperControl > 
template<>
struct DataType< ::osrf_gear::VacuumGripperControlResponse>
{
  static const char* value()
  {
    return DataType< ::osrf_gear::VacuumGripperControl >::value();
  }
  static const char* value(const ::osrf_gear::VacuumGripperControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OSRF_GEAR_MESSAGE_VACUUMGRIPPERCONTROL_H
